language: python

matrix:
  include:
#    - sudo: required
#      services:
#        - docker
#      env:
#        - PIP=pip
#        - PYTHON=python
    - os: osx
      language: generic
      compiler: gcc
      env:
        - PIP=pip2
        - PYTHON=python2

script:
  - cd python
  - git describe --tags >VERSION
  - $PIP install wheel
  - $PYTHON setup.py sdist --dist-dir wheelhouse
  - $PIP install cibuildwheel
  - export CIBW_SKIP='cp34-*'
  - export CIBW_BEFORE_BUILD_LINUX='yum install cmake -y'
  - export CIBW_BUILD_VERBOSITY=3
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      $PYTHON -m twine upload wheelhouse/* --skip-existing --repository-url https://test.pypi.org/legacy/
    fi
