environment:
  TWINE_USERNAME:
    secure: TEiy+eHGeQQIy9jUEpUNMA==
  TWINE_PASSWORD:
    secure: nGYP/oqo/DSfCQduEhhKGg==

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

install:
    - cmd: "%PYTHON%\\python.exe -m pip install wheel"
    - cmd: "%PYTHON%\\python.exe -m pip install pytest"
    - cmd: "%PYTHON%\\python.exe -m pip install twine"

before_build:
    - cd python
    - cmd: "git describe --tags >VERSION"

build_script:
    - cmd: "%PYTHON%\\python.exe setup.py install"

test_script:
    - cmd: "%PYTHON%\\scripts\\pytest.exe"

artifacts:
    # setup.py install runs the bdist_wheel first
    - path: dist\*.whl
      name: wheel

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
deploy_script:
    - ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { twine upload dist\*.whl }
